version: '3.3'
services:
  django_practice:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/healthcheck/"]
      interval: 10s
      timeout: 5s
      retries: 5

